### ISSUE TITLE
1.20.1: Bananarang not hitting enemies

### ISSUE THREAD

**Issue by WimpieRatte** [BrownBear85/bananarangs#1]
When throwing the bananarang, it "mostly" goes right through the enemies.
Sometimes it hits, but it is too unreliable as a weapon.
Also, it would be nice if your hotbar could keep the slot open for the bananarang to return to. Currently, when I pick up items, it takes the place where the bananarang used to be.

Also, would be nice to have an issues link in the Modrinth page ;).
(I found this issues page by going to your other projects on Modrinth and eventually finding your github profile.)

**Comment by BrownBear85** [comment]
The collision bug is fixed with Bananarangs 1.2 for 1.20, 1.20.1.

**Comment by QianFuv** [comment]
Apologies for the inconvenience, would it be possible to apply this bug fix to version 1.19.2?
